import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
import ReactQueryPvorider from "@/providers/ReactQueryPvorider";
import StoreProvider from "@/providers/StoreProvider";

const Shabnam = localFont({
  src: "../../public/fonts/Shabnam.ttf",
  variable: "--font-Shabnam",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body className={`${Shabnam.variable}`}>
        <StoreProvider>
          <ReactQueryPvorider>
            <Header />
            <div className="pt-32 md:pt-48">{children}</div>
            <Footer />
          </ReactQueryPvorider>
        </StoreProvider>
      </body>
    </html>
  );
}
